language: node_js
node_js:
  - '5.5.0'
notifications:
  email: false
before_install:
  - travis_retry nvm install 5.5.0
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm install request;
      npm run update-package;
    fi
env:
  global:
    - secure: "djfqukVJHqSy1XwaXXI98OGAVDI5sHyf8d/DQ9WPLrx/xc/bQXAJgAakgZimRS2NHNNZ9kx4EFDsipT7ZAX3HjSNHP3yvdFNwP1WuuZLnKeowTdOLjcJLqlKZaPLdiICuF71+iICeogzR+VHOv/Ec+DNbKXFFanQQDL40DuVNc8="
    - MERGE_TOKEN=7ec583e95b00bfab262215cb3bb41c5ec822951f
    - SENDGRID_USERNAME=azai91
    - secure: cppYq0mlnrMBbCpw+IAcNmMFTwDLWZobCNdlY5qDhR7yDzQuq4QpZU58xCR02kcWvViyuPweYoyerSmetwDNzcGL3z4ErY0YaP6jGoP/9az1XQpzfYZme/Hov5JVZOhYnRF6k0wgy8P1wAa0GLu1DZveoxfxcxoNIMtTCeH0+9k=
    - secure: aqWoZPpZhYFNjrPWR0ucjqeScXZ62gSbmyTKH3fGmbsxsAswZc+PZJsWxEXtmt+dQWVq9L1SO9s+IO9v8h4NaNQlafkFa5EKUfUQEcHZIjLhFG+LoXljzrfiK4irG/x9+/ZNr1GxOYNUrFXug+D1NCMbJ1UEgc5UfarsTkG7yFc=
    - secure: gyHPFww9XMFUcq/iW+snBSVh7Ooh4cgzbpjTY82cYWJ+U+WUMRHQaTTIxBCi+g3DK2j+91/cUlfLTPi6XYvYgy6Kq6xyN7HfeVhaJ10l1CYopMHPLrkKz/B8u47kLmta5M6dJaEeSQW0RduRQiZHcA3+U9tY+zjeGjiUlJr6w+U=
script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm run get-test-utils && npm run test ; npm run lint ; npm run report;
    else
      npm run merge;
    fi
